### ISSUE TITLE
如何使用注音臺灣正體輸入簡體字

### ISSUE THREAD

**Issue by hchungi** [osfans/PIME#19]
如題！請問如何使用注音臺灣正體輸入簡體字？

謝謝

**Comment by osfans** [comment]
bopomofo.schema.yaml的話，可以臨時用F4切換簡繁。要預設簡體的話，可以添加reset: 1
```yaml
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 漢字, 汉字 ]
    reset: 1
  - name: ascii_punct
    states: [ 。，, ．， ]
```
